const {chromium}=require('C:/Users/test/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Users/test/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe'});
const context=await b.newContext({viewport:{width:1440,height:900},recordVideo:{dir:'.qa/video',size:{width:1440,height:900}}});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto('http://localhost:3000/',{waitUntil:'networkidle'});await p.waitForTimeout(500);await p.getByRole('link',{name:'TRACK PROJECTS',exact:true}).click();await p.waitForURL('**/dashboard');await p.getByText('16,451',{exact:true}).waitFor();await p.waitForTimeout(800);
await p.getByRole('combobox',{name:'Region',exact:true}).selectOption({label:'NCR'});await p.waitForTimeout(100);console.log('FILTER MID',await p.locator('[data-reveal="kpi"]').first().getAttribute('style'));await p.waitForTimeout(600);
await p.getByRole('button',{name:'Directory',exact:true}).click();await p.waitForTimeout(500);console.log('ROWS',await p.locator('tbody tr').count());await p.getByRole('button',{name:'Report Overview',exact:true}).click();await p.waitForTimeout(700);
await p.getByRole('button',{name:'Submit Site Photo',exact:true}).click();await p.waitForTimeout(650);await p.keyboard.press('Escape');await p.waitForTimeout(450);console.log('FOCUS',await p.evaluate(()=>document.activeElement?.textContent));
await p.screenshot({path:'.qa/filtered.png'});console.log('ERRORS',errors);await context.close();
const m=await b.newPage({viewport:{width:390,height:844},isMobile:true,reducedMotion:'reduce'});await m.goto('http://localhost:3000/',{waitUntil:'networkidle'});await m.getByRole('link',{name:'TRACK PROJECTS',exact:true}).click();await m.waitForURL('**/dashboard');await m.getByText('16,451',{exact:true}).waitFor();await m.waitForTimeout(700);await m.screenshot({path:'.qa/mobile.png'});console.log('MOBILE',await m.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches})));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
