export type ReadinessStatus = 'Ready' | 'At risk' | 'Pending' | 'Unknown';
export type BuildingType = string;
export type FacilityCounts={academic?:number;audioVisual:number;computerLab:number;homeEconomics:number;scienceLab:number;workshop:number};
export type SchoolProject = { id:string; recordId?:string; projectId?:string|null; name:string; region:string; division:string; municipality:string; buildingType:BuildingType; classrooms:number; readiness:ReadinessStatus; demolition:boolean; siteImprovement:boolean; slopeProtection:boolean; lat:number|null; lng:number|null; facilities?:FacilityCounts; floors:number; completion:number };
export const projects:SchoolProject[] = [
  {id:'502649',name:'Malayugan ES/IS',region:'CAR',division:'Apayao',municipality:'Flora',buildingType:'Low-rise',classrooms:8,readiness:'Ready',demolition:false,siteImprovement:true,slopeProtection:true,lat:18.21,lng:121.42,floors:2,completion:100,facilities:{audioVisual:1,computerLab:1,homeEconomics:1,scienceLab:1,workshop:1}},
  {id:'134966',name:'Agtangao Elementary School',region:'CAR',division:'Abra',municipality:'Bangued',buildingType:'Low-rise',classrooms:8,readiness:'Pending',demolition:false,siteImprovement:true,slopeProtection:false,lat:17.60,lng:120.61,floors:2,completion:78},
  {id:'136382',name:'Baguio Central School',region:'CAR',division:'Baguio City',municipality:'Baguio',buildingType:'Mid-rise',classrooms:24,readiness:'Ready',demolition:true,siteImprovement:false,slopeProtection:true,lat:16.41,lng:120.59,floors:4,completion:100},
  {id:'108721',name:'Laoag Central Elementary School',region:'Region I',division:'Laoag City',municipality:'Laoag',buildingType:'Mid-rise',classrooms:20,readiness:'At risk',demolition:true,siteImprovement:true,slopeProtection:false,lat:18.20,lng:120.59,floors:4,completion:43},
  {id:'300991',name:'Tuguegarao National High School',region:'Region II',division:'Tuguegarao City',municipality:'Tuguegarao',buildingType:'High-rise',classrooms:30,readiness:'Pending',demolition:false,siteImprovement:true,slopeProtection:false,lat:17.61,lng:121.73,floors:5,completion:68},
  {id:'105442',name:'San Fernando Elementary School',region:'Region III',division:'Pampanga',municipality:'San Fernando',buildingType:'Mid-rise',classrooms:20,readiness:'Ready',demolition:false,siteImprovement:false,slopeProtection:false,lat:15.03,lng:120.69,floors:4,completion:100},
  {id:'137201',name:'Commonwealth Elementary School',region:'NCR',division:'Quezon City',municipality:'Quezon City',buildingType:'High-rise',classrooms:40,readiness:'Ready',demolition:true,siteImprovement:true,slopeProtection:false,lat:14.68,lng:121.08,floors:5,completion:100},
  {id:'110842',name:'Calamba Integrated School',region:'Region IV-A',division:'Laguna',municipality:'Calamba',buildingType:'High-rise',classrooms:40,readiness:'At risk',demolition:false,siteImprovement:true,slopeProtection:true,lat:14.21,lng:121.17,floors:5,completion:39},
  {id:'126504',name:'Calapan City National High School',region:'Region IV-B',division:'Oriental Mindoro',municipality:'Calapan',buildingType:'Mid-rise',classrooms:20,readiness:'Pending',demolition:true,siteImprovement:false,slopeProtection:false,lat:13.41,lng:121.18,floors:4,completion:74},
  {id:'114904',name:'Naga Central School I',region:'Region V',division:'Naga City',municipality:'Naga',buildingType:'Low-rise',classrooms:10,readiness:'Ready',demolition:false,siteImprovement:true,slopeProtection:false,lat:13.62,lng:123.19,floors:2,completion:100},
];
export const reportTotals={classrooms:16451,schools:1093,academic:14889,special:1568,readyRate:72};
export type ProjectFilters={region:string;division:string;buildingType:string;readiness:string;scope:string;search:string};
export const projectRepository={getProjects:()=>projects,getProject:(id:string)=>projects.find(p=>p.id===id),getFilterOptions:()=>({regions:Array.from(new Set(projects.map(p=>p.region))),divisions:Array.from(new Set(projects.map(p=>p.division))),buildingTypes:Array.from(new Set(projects.map(p=>p.buildingType)))})};
