'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import PsipMap from '@/components/psip-map';
import {createColumnHelper,flexRender,getCoreRowModel,getSortedRowModel,SortingState,useReactTable} from '@tanstack/react-table';
import {Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,XAxis,YAxis} from 'recharts';
import {Activity,ArrowUpDown,Building2,Check,CheckCircle2,ChevronDown,Clock3,FlaskConical,GraduationCap,MapPinned,Search,ShieldAlert,SlidersHorizontal,X,Monitor, Wrench, Home, Mic} from 'lucide-react';
import {ChartContainer,ChartTooltip,ChartTooltipContent} from '@/components/ui/chart';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {projectRepository,projects,ProjectFilters,reportTotals,SchoolProject} from '@/lib/psip-data';

const number=new Intl.NumberFormat('en-US');
const blank:ProjectFilters={region:'',division:'',buildingType:'',readiness:'',scope:'',search:''};
const readinessColor={Ready:'#19a974',Pending:'#e1a11a','At risk':'#d94b5b'};
const buildingColors=['#1854bd','#19a974','#f1b84b'];
const col=createColumnHelper<SchoolProject>();

function appliesScope(p:SchoolProject,scope:string){return !scope||(scope==='Demolition'&&p.demolition)||(scope==='Site improvement'&&p.siteImprovement)||(scope==='Slope protection'&&p.slopeProtection)}

export default function DashboardPage(){
 const [filters,setFilters]=useState<ProjectFilters>(blank);
 const [selected,setSelected]=useState<SchoolProject|null>(null);
 const [sorting,setSorting]=useState<SortingState>([]);
 const opts=projectRepository.getFilterOptions();
 useEffect(()=>{const q=new URLSearchParams(location.search);setFilters({region:q.get('region')||'',division:q.get('division')||'',buildingType:q.get('building')||'',readiness:q.get('readiness')||'',scope:q.get('scope')||'',search:q.get('search')||''});const school=q.get('school');if(school)setSelected(projectRepository.getProject(school)||null)},[]);
 useEffect(()=>{const q=new URLSearchParams();Object.entries(filters).forEach(([k,v])=>{if(v)q.set(k==='buildingType'?'building':k,v)});if(selected)q.set('school',selected.id);history.replaceState(null,'',`/dashboard${q.size?`?${q}`:''}`)},[filters,selected]);
 const filtered=useMemo(()=>projects.filter(p=>(!filters.region||p.region===filters.region)&&(!filters.division||p.division===filters.division)&&(!filters.buildingType||p.buildingType===filters.buildingType)&&(!filters.readiness||p.readiness===filters.readiness)&&appliesScope(p,filters.scope)&&(!filters.search||`${p.id} ${p.name} ${p.division}`.toLowerCase().includes(filters.search.toLowerCase()))),[filters]);
 const regionData=useMemo(()=>Array.from(new Set(filtered.map(p=>p.region))).map(region=>({region,classrooms:filtered.filter(p=>p.region===region).reduce((s,p)=>s+p.classrooms,0),sites:filtered.filter(p=>p.region===region).length})).sort((a,b)=>b.classrooms-a.classrooms),[filtered]);
 const buildingData=useMemo(()=>opts.buildingTypes.map((name,i)=>({name,value:filtered.filter(p=>p.buildingType===name).length,color:buildingColors[i]})),[filtered,opts.buildingTypes]);
 const active=Object.entries(filters).filter(([,v])=>v);
 const columns=useMemo(()=>[
  col.accessor('region',{header:'Region'}),col.accessor('division',{header:'Division'}),col.accessor('id',{header:'School ID'}),col.accessor('name',{header:'School',cell:i=><button className="font-semibold text-[#164da8] hover:underline" onClick={()=>setSelected(i.row.original)}>{i.getValue()}</button>}),col.accessor('buildingType',{header:'Building'}),col.accessor('classrooms',{header:'Rooms'}),col.accessor('completion',{header:'Progress',cell:i=><div className="flex min-w-24 items-center gap-2"><span className="h-1.5 w-16 rounded-full bg-[#e9edf4]"><span className="block h-full rounded-full bg-[#2366dc]" style={{width:`${i.getValue()}%`}}/></span><span className="text-xs">{i.getValue()}%</span></div>}),col.accessor('readiness',{header:'Readiness',cell:i=><Status value={i.getValue()}/>}),
 ],[]);
 const table=useReactTable({data:filtered,columns,state:{sorting},onSortingChange:setSorting,getCoreRowModel:getCoreRowModel(),getSortedRowModel:getSortedRowModel()});
 const update=(key:keyof ProjectFilters,value:string)=>setFilters(f=>({...f,[key]:value}));
 return <main className="min-h-screen pb-10">
  <AppHeader/>
  <section className="border-b bg-white"><div className="mx-auto max-w-[1500px] px-5 py-6 lg:px-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.15em] text-[#2366dc]"><Activity className="size-4"/>National command center</p><h1 className="text-3xl font-bold tracking-[-.04em] sm:text-4xl">School infrastructure at a glance</h1><p className="mt-2 max-w-2xl text-sm text-[#526079]">Track classroom delivery, site readiness, and regional project needs across the PSIP III portfolio.</p></div><div className="flex flex-wrap gap-2"><FilterSelect label="Region" value={filters.region} onChange={v=>update('region',v)} options={opts.regions}/><FilterSelect label="Readiness" value={filters.readiness} onChange={v=>update('readiness',v)} options={['Ready','Pending','At risk']}/></div></div></div></section>
  <div className="mx-auto max-w-[1500px] space-y-5 px-5 py-5 lg:px-8">
   <section className="rounded-2xl border bg-white p-3 shadow-[0_8px_24px_rgba(21,48,93,.04)]" aria-label="Dashboard filters"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_1fr_auto]"><label className="relative"><span className="sr-only">Search schools</span><Search className="pointer-events-none absolute left-3 top-3 size-4 text-[#6b7890]"/><input value={filters.search} onChange={e=>update('search',e.target.value)} placeholder="Search school, ID, or division" className="h-10 w-full rounded-xl border bg-[#f8fafd] pl-9 pr-3 text-sm"/></label><FilterSelect label="Division" value={filters.division} onChange={v=>update('division',v)} options={opts.divisions}/><FilterSelect label="Building" value={filters.buildingType} onChange={v=>update('buildingType',v)} options={opts.buildingTypes}/><FilterSelect label="Project scope" value={filters.scope} onChange={v=>update('scope',v)} options={['Demolition','Site improvement','Slope protection']}/><button onClick={()=>setFilters(blank)} disabled={!active.length} className="flex h-10 items-center justify-center gap-2 rounded-xl border px-4 text-sm font-semibold disabled:opacity-40"><X className="size-4"/>Clear</button></div>{active.length>0&&<div className="mt-3 flex flex-wrap gap-2 border-t pt-3">{active.map(([k,v])=><button key={k} onClick={()=>update(k as keyof ProjectFilters,'')} className="flex items-center gap-1 rounded-full bg-[#eaf0fb] px-3 py-1 text-xs font-semibold text-[#164da8]">{v}<X className="size-3"/></button>)}</div>}</section>
   <ClassificationPanel/>
   {filtered.length===0?<Empty onClear={()=>setFilters(blank)}/>:<>
    <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><MapPanel data={filtered} onSelect={setSelected}/><ReadinessPanel data={filtered}/></section>
    <section className="grid gap-5 lg:grid-cols-2"><ChartCard eyebrow="Regional delivery" title="Planned classrooms by region"><ChartContainer config={{classrooms:{label:'Classrooms',color:'#1854bd'}}} className="h-[270px] w-full"><BarChart data={regionData} margin={{left:-18,right:12}} onClick={(state)=>{const label=(state as {activeLabel?:string})?.activeLabel;if(label)update('region',label)}}><CartesianGrid vertical={false}/><XAxis dataKey="region" tickLine={false} axisLine={false} fontSize={10}/><YAxis tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="classrooms" fill="var(--color-classrooms)" radius={[6,6,0,0]} cursor="pointer"/></BarChart></ChartContainer></ChartCard>
    <ChartCard eyebrow="Building portfolio" title="Projects by building type"><div className="grid items-center sm:grid-cols-[1fr_180px]"><ChartContainer config={{value:{label:'Projects'}}} className="h-[250px] w-full"><PieChart><Pie data={buildingData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={88} paddingAngle={3} onClick={d=>update('buildingType',d.name)}>{buildingData.map(d=><Cell key={d.name} fill={d.color}/>)}</Pie><ChartTooltip content={<ChartTooltipContent hideLabel/>}/></PieChart></ChartContainer><div className="space-y-3">{buildingData.map(d=><button key={d.name} onClick={()=>update('buildingType',d.name)} className="flex w-full items-center justify-between rounded-lg px-2 py-1 text-sm hover:bg-[#f3f6fb]"><span><span className="mr-2 inline-block size-2 rounded-full" style={{background:d.color}}/>{d.name}</span><b>{d.value}</b></button>)}</div></div></ChartCard></section>
    <SchoolTable table={table}/>
   </>}
  </div>
  <SchoolPreview school={selected} onClose={()=>setSelected(null)}/>
 </main>
}

function AppHeader(){return <header className="bg-[#0b245f] text-white"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-6 px-5 py-4 lg:px-8"><Link href="/dashboard" className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white text-[#123b8f]"><Building2 className="size-5"/></div><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-blue-200">Department of Education</p><p className="font-semibold tracking-tight">PSIP Monitor</p></div></Link><nav className="hidden items-center gap-1 rounded-xl bg-white/8 p-1 md:flex" aria-label="Primary navigation"><Link className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-[#123b8f]" href="/dashboard">Overview</Link><span className="px-4 py-2 text-sm text-blue-100">Schools</span><span className="px-4 py-2 text-sm text-blue-100">Readiness</span></nav><div className="text-right"><p className="text-xs text-blue-200">Data snapshot</p><p className="text-sm font-semibold">01 September 2026</p></div></div></header>}
function FilterSelect({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="relative"><span className="sr-only">{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full appearance-none rounded-xl border bg-white pl-3 pr-9 text-sm font-semibold"><option value="">{label}</option>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown className="pointer-events-none absolute right-3 top-3 size-4 text-[#526079]"/></label>}
function Status({value}:{value:SchoolProject['readiness']}){const Icon=value==='Ready'?CheckCircle2:value==='At risk'?ShieldAlert:Clock3;return <span className="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold" style={{background:`${readinessColor[value]}18`,color:readinessColor[value]}}><Icon className="size-3.5"/>{value}</span>}
function ClassificationPanel(){const rows=[['Academic Classroom',14889,GraduationCap,'#1854bd'],['Computer Laboratory',465,Monitor,'#1854bd'],['Science Laboratory',421,FlaskConical,'#1854bd'],['Workshop',313,Wrench,'#1854bd'],['Home Economics',187,Home,'#1854bd'],['Audio Visual Room',182,Mic,'#1854bd']] as const;const max=rows[0][1];return <section aria-label="Classroom classification" className="overflow-hidden rounded-2xl border bg-white shadow-[0_8px_24px_rgba(21,48,93,.05)]"><div className="flex items-center justify-between border-b bg-[#f7f9fd] px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-[#2366dc]">Portfolio mix</p><h2 className="mt-1 text-xl font-bold">Classrooms classification</h2></div><span className="rounded-full bg-[#e8f7f1] px-3 py-1 text-xs font-bold text-[#087a54]">16,457 rooms</span></div><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{rows.map(([label,value,Icon,color])=><article key={label} className="rounded-xl border bg-white p-3 transition-shadow hover:shadow-[0_8px_20px_rgba(21,48,93,.08)]"><div className="flex h-20 items-center justify-center rounded-lg bg-[#f8fafd] text-[#1854bd]"><Icon className="size-10" strokeWidth={1.7}/></div><div className="mt-3 flex items-start justify-between gap-2"><p className="text-xs font-semibold leading-4 text-[#526079]">{label}</p><b className="text-sm text-[#0b245f]">{number.format(value)}</b></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#e9edf4]"><span className="block h-full rounded-full" style={{width:`${Math.max(7,value/max*100)}%`,background:color}}/></div><p className="mt-2 text-[11px] text-[#7b879d]">{(value/max*100).toFixed(1)}% of rooms</p></article>)}</div></section>}
function MapPanel({data,onSelect}:{data:SchoolProject[];onSelect:(p:SchoolProject)=>void}){return <article className="min-h-[420px] overflow-hidden rounded-2xl border bg-white shadow-[0_8px_24px_rgba(21,48,93,.05)]"><div className="flex items-start justify-between border-b p-5"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-[#2366dc]">Regional portfolio</p><h2 className="mt-1 text-xl font-bold">School sites across the Philippines</h2></div><span className="rounded-full bg-[#e8f7f1] px-3 py-1 text-xs font-bold text-[#087a54]">{data.length} visible</span></div><div className="relative h-[340px]"><PsipMap projects={data} onSelect={onSelect}/><div className="pointer-events-none absolute bottom-4 left-4 z-[500] rounded-xl border bg-white/95 px-3 py-2 text-xs text-[#526079] shadow-sm"><span className="mr-2 inline-block size-2 rounded-full bg-[#19a974]"/>Ready <span className="mx-2 inline-block size-2 rounded-full bg-[#e1a11a]"/>Pending <span className="mx-2 inline-block size-2 rounded-full bg-[#d94b5b]"/>At risk</div></div></article>}
function ReadinessPanel({data}:{data:SchoolProject[]}){const counts={Ready:data.filter(p=>p.readiness==='Ready').length,Pending:data.filter(p=>p.readiness==='Pending').length,'At risk':data.filter(p=>p.readiness==='At risk').length};const total=data.length;const rate=Math.round(counts.Ready/total*100);return <article className="rounded-2xl bg-[#0d2d70] p-5 text-white shadow-[0_14px_30px_rgba(11,36,95,.16)]"><p className="text-xs font-bold uppercase tracking-[.13em] text-blue-200">Visible readiness</p><div className="my-8 flex flex-wrap items-center gap-6"><div className="grid size-36 place-items-center rounded-full" style={{background:`conic-gradient(#33d69f 0 ${rate}%,#f1b84b ${rate}% ${Math.min(100,rate+Math.round(counts.Pending/total*100))}%,#e55c68 0)`}}><div className="grid size-28 place-items-center rounded-full bg-[#0d2d70]"><div className="text-center"><strong className="text-3xl">{rate}%</strong><p className="text-[10px] text-blue-200">Ready</p></div></div></div><div className="min-w-40 flex-1 space-y-3 text-sm">{Object.entries(counts).map(([k,v])=><p key={k}><span className="mr-2 inline-block size-2 rounded-full" style={{background:readinessColor[k as keyof typeof readinessColor]}}/>{k}<b className="float-right">{v}</b></p>)}</div></div><div className="rounded-xl bg-white/8 p-4"><p className="text-sm font-semibold">Readiness is improving</p><p className="mt-1 text-xs leading-5 text-blue-200">Use the status filters to isolate sites that need action or final validation.</p></div></article>}
function ChartCard({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <article className="rounded-2xl border bg-white p-5 shadow-[0_8px_24px_rgba(21,48,93,.05)]"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#2366dc]">{eyebrow}</p><h2 className="mb-3 mt-1 text-xl font-bold">{title}</h2>{children}</article>}
function SchoolTable({table}:{table:ReturnType<typeof useReactTable<SchoolProject>>}){return <section className="overflow-hidden rounded-2xl border bg-white shadow-[0_8px_24px_rgba(21,48,93,.05)]"><div className="flex items-end justify-between gap-4 border-b p-5"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-[#2366dc]">Project directory</p><h2 className="mt-1 text-xl font-bold">School building readiness</h2></div><p className="text-xs text-[#647089]">Select a school for a quick preview</p></div><Table><TableHeader><TableRow>{table.getFlatHeaders().map(h=><TableHead key={h.id}><button className="flex items-center gap-1 font-bold" onClick={h.column.getToggleSortingHandler()}>{flexRender(h.column.columnDef.header,h.getContext())}<ArrowUpDown className="size-3"/></button></TableHead>)}</TableRow></TableHeader><TableBody>{table.getRowModel().rows.map(row=><TableRow key={row.id}>{row.getVisibleCells().map(cell=><TableCell key={cell.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</TableCell>)}</TableRow>)}</TableBody></Table></section>}
function SchoolPreview({school,onClose}:{school:SchoolProject|null;onClose:()=>void}){if(!school)return null;const facilities=school.facilities||{audioVisual:0,computerLab:1,homeEconomics:0,scienceLab:1,workshop:0};return <Sheet open={!!school} onOpenChange={o=>!o&&onClose()}><SheetContent side="right" className="w-full overflow-y-auto p-0 sm:max-w-[480px]"><div className="bg-[#0b245f] px-6 pb-6 pt-10 text-white"><SheetHeader className="p-0"><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-200">School projects overview</p><SheetTitle className="mt-2 text-2xl font-bold text-white">{school.name}</SheetTitle><SheetDescription className="text-blue-100">{school.municipality}, {school.division} · {school.region}</SheetDescription></SheetHeader><div className="mt-5 flex items-center justify-between rounded-xl bg-white/10 p-3"><span className="text-sm">Operational readiness</span><Status value={school.readiness}/></div></div><div className="space-y-5 p-6"><div className="grid grid-cols-3 gap-3"><Mini label="Classrooms" value={school.classrooms}/><Mini label="Floors" value={school.floors}/><Mini label="Complete" value={`${school.completion}%`}/></div><div><h3 className="mb-3 font-bold">Special facilities</h3><div className="grid grid-cols-2 gap-2 text-sm">{Object.entries(facilities).map(([k,v])=><div key={k} className="rounded-xl bg-[#f4f7fb] p-3"><p className="text-xs capitalize text-[#647089]">{k.replace(/([A-Z])/g,' $1')}</p><b>{v}</b></div>)}</div></div><div><h3 className="mb-3 font-bold">Scope of works</h3><div className="space-y-2"><Scope label="Site improvement" active={school.siteImprovement}/><Scope label="Slope protection" active={school.slopeProtection}/><Scope label="For demolition" active={school.demolition}/></div></div><Link href={`/schools/${school.id}`} className="flex h-11 items-center justify-center rounded-xl bg-[#1854bd] font-bold text-white hover:bg-[#0b245f]">Open full details</Link></div></SheetContent></Sheet>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border p-3 text-center"><b className="text-xl">{value}</b><p className="text-xs text-[#647089]">{label}</p></div>}
function Scope({label,active}:{label:string;active:boolean}){return <div className="flex items-center justify-between rounded-xl border px-3 py-2.5 text-sm"><span>{label}</span><span className={`grid size-6 place-items-center rounded-full ${active?'bg-[#ddf7ec] text-[#087a54]':'bg-[#f0f2f6] text-[#8490a3]'}`}>{active?<Check className="size-4"/>:<X className="size-4"/>}</span></div>}
function Empty({onClear}:{onClear:()=>void}){return <section className="grid min-h-80 place-items-center rounded-2xl border border-dashed bg-white p-8 text-center"><div><div className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#eaf0fb] text-[#1854bd]"><Search/></div><h2 className="mt-4 text-xl font-bold">No projects match these filters</h2><p className="mt-2 text-sm text-[#647089]">Clear the current selection to return to the national portfolio.</p><button onClick={onClear} className="mt-4 rounded-xl bg-[#1854bd] px-4 py-2 text-sm font-bold text-white">Clear filters</button></div></section>}
