import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft,Building2,Check,CheckCircle2,Clock3,FlaskConical,GraduationCap,MapPin,ShieldAlert,X} from 'lucide-react';
import type {SchoolProject} from '@/lib/psip-data';
import {fetchSchool} from '@/lib/psip-api';

export async function generateMetadata({params}:{params:Promise<{schoolId:string}>}):Promise<Metadata>{const {schoolId}=await params;const school=await fetchSchool(schoolId).catch(()=>null);if(!school)return {title:'School not found'};return {title:school.name,description:`${school.name} infrastructure project status and readiness.`,openGraph:{title:school.name,description:`${school.name} infrastructure project status and readiness.`,images:[]},twitter:{title:school.name,description:`${school.name} infrastructure project status and readiness.`,images:[]}}}

export default async function SchoolPage({params}:{params:Promise<{schoolId:string}>}){const {schoolId}=await params;const school=await fetchSchool(schoolId).catch(()=>null);if(!school)notFound();const facilities=school.facilities||{audioVisual:0,computerLab:1,homeEconomics:0,scienceLab:1,workshop:0};return <main className="min-h-screen pb-12"><Header/><div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><Link href="/dashboard" className="mb-6 inline-flex h-10 items-center gap-2 rounded-xl border bg-white px-4 text-sm font-bold text-[#164da8] hover:bg-[#f5f8fd]"><ArrowLeft className="size-4"/>Back to dashboard</Link>
 <section className="overflow-hidden rounded-3xl bg-[#0b245f] text-white shadow-[0_18px_45px_rgba(11,36,95,.18)]"><div className="grid gap-8 p-6 md:grid-cols-[1fr_auto] md:p-9"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-blue-200">School project · {school.id}</p><h1 className="mt-3 text-3xl font-bold tracking-[-.04em] md:text-5xl">{school.name}</h1><p className="mt-3 flex items-center gap-2 text-blue-100"><MapPin className="size-4"/>{school.municipality}, {school.division} · {school.region}</p></div><div className="min-w-52 rounded-2xl bg-white/10 p-5"><p className="text-xs font-bold uppercase tracking-wider text-blue-200">Operational readiness</p><div className="mt-3"><Status value={school.readiness}/></div><p className="mt-5 text-sm font-bold">{school.projectId||'No project reference'}</p><p className="text-xs text-blue-200">Fabric project reference</p></div></div></section>
 <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={GraduationCap} label="Planned classrooms" value={school.classrooms}/><Metric icon={Building2} label="Building profile" value={`${school.floors} floors`}/><Metric icon={FlaskConical} label="Special facilities" value={Object.values(facilities).reduce((a,b)=>a+b,0)}/><Metric icon={CheckCircle2} label="Delivery status" value={school.readiness}/></section>
 <section className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article className="rounded-2xl border bg-white p-6 shadow-[0_8px_24px_rgba(21,48,93,.05)]"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#2366dc]">Learning spaces</p><h2 className="mt-1 text-xl font-bold">Classroom and facility plan</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(facilities).map(([k,v])=><div key={k} className="flex items-center justify-between rounded-xl bg-[#f4f7fb] p-4"><span className="text-sm capitalize text-[#526079]">{k.replace(/([A-Z])/g,' $1')}</span><b className="text-lg">{v}</b></div>)}</div></article>
 <article className="rounded-2xl border bg-white p-6 shadow-[0_8px_24px_rgba(21,48,93,.05)]"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#2366dc]">Scope and readiness</p><h2 className="mt-1 text-xl font-bold">Site work requirements</h2><div className="mt-5 space-y-3"><Scope label="Site improvement" active={school.siteImprovement}/><Scope label="Slope protection" active={school.slopeProtection}/><Scope label="For demolition" active={school.demolition}/></div><div className="mt-6 rounded-xl bg-[#edf4ff] p-4"><p className="text-sm font-bold text-[#164da8]">Building specification</p><p className="mt-1 text-sm text-[#526079]">{school.buildingType} · {school.floors} storey · {school.classrooms} classroom package</p></div></article></section>
 <section className="mt-5 grid gap-5 md:grid-cols-3"><Info title="Region" value={school.region}/><Info title="Schools division" value={school.division}/><Info title="Municipality" value={school.municipality}/></section>
 </div></main>}

function Header(){return <header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/dashboard" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#0b245f] text-white"><Building2 className="size-5"/></span><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#61708a]">Department of Education</p><p className="font-bold">PSIP Monitor</p></div></Link><p className="text-xs text-[#61708a]">Project detail</p></div></header>}
function Metric({icon:Icon,label,value}:{icon:typeof Building2;label:string;value:string|number}){return <article className="rounded-2xl border bg-white p-5 shadow-[0_8px_24px_rgba(21,48,93,.05)]"><span className="grid size-9 place-items-center rounded-xl bg-[#eaf0fb] text-[#1854bd]"><Icon className="size-4"/></span><p className="mt-5 text-xs font-semibold text-[#647089]">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></article>}
function Status({value}:{value:SchoolProject['readiness']}){const color=value==='Ready'?'#33d69f':value==='At risk'?'#ff7b87':value==='Pending'?'#f1b84b':'#94a3b8';const Icon=value==='Ready'?CheckCircle2:value==='At risk'?ShieldAlert:Clock3;return <span className="inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-sm font-bold" style={{background:`${color}20`,color}}><Icon className="size-4"/>{value}</span>}
function Scope({label,active}:{label:string;active:boolean}){return <div className="flex items-center justify-between rounded-xl border px-4 py-3 text-sm"><span>{label}</span><span className={`grid size-7 place-items-center rounded-full ${active?'bg-[#ddf7ec] text-[#087a54]':'bg-[#f0f2f6] text-[#8490a3]'}`}>{active?<Check className="size-4"/>:<X className="size-4"/>}</span></div>}
function Info({title,value}:{title:string;value:string}){return <article className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#647089]">{title}</p><p className="mt-2 font-bold">{value}</p></article>}
